INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (1, 'Programação', 'Algoritmos');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (2, 'Programação', 'Estrutura de Dados');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (3, 'Programação', 'Lógica de Programação');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (4, 'Desenvolvimento Backend', 'Java SE');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (5, 'Desenvolvimento Backend', 'Java EE');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (6, 'Desenvolvimento Backend', 'Javascript');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (7, 'Desenvolvimento Backend', 'NodeJs');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (8, 'Desenvolvimento Backend', 'Python');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (9, 'Desenvolvimento Backend', 'PHP');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (10, 'Desenvolvimento Frontend', 'HTML');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (11, 'Desenvolvimento Frontend', 'CSS');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (12, 'Desenvolvimento Frontend', 'Angular');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (13, 'Desenvolvimento Frontend', 'Angular Js');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (14, 'Desenvolvimento Frontend', 'React Js');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (15, 'Desenvolvimento Frontend', 'Vue');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (16, 'Desenvolvimento Frontend', 'Boas Práticas no Frontend');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (17, 'Desenvolvimento Frontend', 'Mean Stack');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (18, 'Desenvolvimento Frontend', 'Angular');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (19, 'Desenvolvimento Frontend', 'React Js');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (20, 'Desenvolvimento Frontend', 'Vue JS');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (21, 'Desenvolvimento Mobile', 'Android Nativo');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (22, 'Desenvolvimento Mobile', 'Ionic Framework');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (23, 'Desenvolvimento Mobile', 'Fluttler Framework');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (24, 'Desenvolvimento Mobile', 'React Native');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (25, 'Desenvolvimento Ágil', 'Scrum Framework');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (26, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (27, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (28, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (29, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (30, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (31, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (32, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (33, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (34, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (35, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (36, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (37, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (38, 'DevOps e Infraestrutura', 'Introdução ao Devops');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (39, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (40, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (41, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (42, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (43, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (44, 'Design e UX', 'Adobe e Suas Ferramentas');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (45, 'Gestão e Inovação', 'Agile Framework');
INSERT INTO db_comunidade.cursos (id, categoria, nome) VALUES (46, 'Gestão e Inovação', 'Scrum Framework');
